import type { Employee, BreakEntry } from "./types"

export const defaultEmployees: Employee[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    department: "Customer Service",
    position: "Senior Representative",
    email: "sarah.johnson@company.com",
    phone: "(555) 123-4567",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Michael Chen",
    department: "Technical Support",
    position: "Support Specialist",
    email: "michael.chen@company.com",
    phone: "(555) 234-5678",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    department: "Sales",
    position: "Account Manager",
    email: "emily.rodriguez@company.com",
    phone: "(555) 345-6789",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "David Kim",
    department: "Operations",
    position: "Operations Coordinator",
    email: "david.kim@company.com",
    phone: "(555) 456-7890",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const defaultBreakEntries: BreakEntry[] = [
  {
    id: "1",
    employeeId: "1",
    employeeName: "Sarah Johnson",
    date: new Date().toISOString().split("T")[0],
    break1Start: "10:00",
    break1End: "10:15",
    break1Coverage: "Michael Chen",
    break2Start: "14:00",
    break2End: "14:15",
    break2Coverage: "",
    notes: "Regular break schedule",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    employeeId: "2",
    employeeName: "Michael Chen",
    date: new Date().toISOString().split("T")[0],
    break1Start: "10:15",
    break1End: "10:30",
    break1Coverage: "Emily Rodriguez",
    break2Start: "14:15",
    break2End: "14:30",
    break2Coverage: "David Kim",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
