import type { Employee, BreakEntry } from "./types"

export const sampleEmployees: Employee[] = [
  {
    id: "1",
    name: "John Smith",
    position: "Cashier",
    department: "Front End",
    email: "john.smith@company.com",
    phone: "(555) 123-4567",
    startDate: "2023-01-15",
    status: "active",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    position: "Sales Associate",
    department: "Sales Floor",
    email: "sarah.johnson@company.com",
    phone: "(555) 234-5678",
    startDate: "2023-02-20",
    status: "active",
  },
  {
    id: "3",
    name: "Mike Davis",
    position: "Stock Clerk",
    department: "Warehouse",
    email: "mike.davis@company.com",
    phone: "(555) 345-6789",
    startDate: "2023-03-10",
    status: "active",
  },
  {
    id: "4",
    name: "Emily Wilson",
    position: "Customer Service",
    department: "Front End",
    email: "emily.wilson@company.com",
    phone: "(555) 456-7890",
    startDate: "2023-04-05",
    status: "active",
  },
  {
    id: "5",
    name: "David Brown",
    position: "Department Manager",
    department: "Electronics",
    email: "david.brown@company.com",
    phone: "(555) 567-8901",
    startDate: "2022-11-12",
    status: "active",
  },
]

export const sampleBreakEntries: BreakEntry[] = [
  {
    id: "1",
    employeeId: "1",
    employeeName: "John Smith",
    date: "2024-01-15",
    shiftStart: "09:00",
    shiftEnd: "17:00",
    break1Start: "11:00",
    break1End: "11:15",
    break1Coverage: "Sarah Johnson",
    break2Start: "14:00",
    break2End: "14:30",
    break2Coverage: "",
    notes: "Lunch break coverage needed",
    status: "completed",
  },
  {
    id: "2",
    employeeId: "2",
    employeeName: "Sarah Johnson",
    date: "2024-01-15",
    shiftStart: "10:00",
    shiftEnd: "18:00",
    break1Start: "12:00",
    break1End: "12:15",
    break1Coverage: "Mike Davis",
    break2Start: "15:00",
    break2End: "15:30",
    break2Coverage: "",
    notes: "",
    status: "completed",
  },
  {
    id: "3",
    employeeId: "3",
    employeeName: "Mike Davis",
    date: "2024-01-15",
    shiftStart: "08:00",
    shiftEnd: "16:00",
    break1Start: "10:00",
    break1End: "10:15",
    break1Coverage: "David Brown",
    break2Start: "13:00",
    break2End: "13:30",
    break2Coverage: "Emily Wilson",
    notes: "All breaks covered",
    status: "completed",
  },
  {
    id: "4",
    employeeId: "4",
    employeeName: "Emily Wilson",
    date: "2024-01-16",
    shiftStart: "11:00",
    shiftEnd: "19:00",
    break1Start: "13:30",
    break1End: "13:45",
    break1Coverage: "",
    break2Start: "16:30",
    break2End: "17:00",
    break2Coverage: "",
    notes: "Need coverage for both breaks",
    status: "scheduled",
  },
  {
    id: "5",
    employeeId: "5",
    employeeName: "David Brown",
    date: "2024-01-16",
    shiftStart: "07:00",
    shiftEnd: "15:00",
    break1Start: "09:30",
    break1End: "09:45",
    break1Coverage: "John Smith",
    break2Start: "12:30",
    break2End: "13:00",
    break2Coverage: "",
    notes: "Manager shift - lunch coverage needed",
    status: "in-progress",
  },
]

export const initialEmployees = sampleEmployees
export const initialBreakEntries = sampleBreakEntries
