import type { Employee, BreakEntry } from "./types"

export const defaultEmployees: Employee[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    department: "Customer Service",
    position: "Senior Representative",
    email: "sarah.johnson@company.com",
    phone: "(555) 123-4567",
    hireDate: "2022-03-15",
    isActive: true,
  },
  {
    id: "2",
    name: "Michael Chen",
    department: "Sales",
    position: "Account Manager",
    email: "michael.chen@company.com",
    phone: "(555) 234-5678",
    hireDate: "2021-08-22",
    isActive: true,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    department: "Customer Service",
    position: "Team Lead",
    email: "emily.rodriguez@company.com",
    phone: "(555) 345-6789",
    hireDate: "2020-11-10",
    isActive: true,
  },
  {
    id: "4",
    name: "David Kim",
    department: "Technical Support",
    position: "Support Specialist",
    email: "david.kim@company.com",
    phone: "(555) 456-7890",
    hireDate: "2023-01-05",
    isActive: true,
  },
  {
    id: "5",
    name: "Lisa Thompson",
    department: "Sales",
    position: "Sales Representative",
    email: "lisa.thompson@company.com",
    phone: "(555) 567-8901",
    hireDate: "2022-09-18",
    isActive: false,
  },
]

export const defaultBreakEntries: BreakEntry[] = [
  {
    id: "1",
    employeeId: "1",
    date: new Date().toISOString().split("T")[0],
    break1Start: "10:00",
    break1End: "10:15",
    break1Coverage: "Emily Rodriguez",
    break2Start: "14:00",
    break2End: "14:15",
    break2Coverage: "",
    notes: "Regular break schedule",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    employeeId: "2",
    date: new Date().toISOString().split("T")[0],
    break1Start: "10:30",
    break1End: "10:45",
    break1Coverage: "David Kim",
    break2Start: "14:30",
    break2End: "14:45",
    break2Coverage: "Sarah Johnson",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    employeeId: "3",
    date: new Date().toISOString().split("T")[0],
    break1Start: "09:30",
    break1End: "09:45",
    break1Coverage: "",
    break2Start: "13:30",
    break2End: "13:45",
    break2Coverage: "Michael Chen",
    notes: "Team lead schedule",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
